name: eslint CI


on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install modules
        run: npm install --force

      - name: run lint
        run: npm run lint -- --fix

      - name: run check
        run: npm run checkH
